/*
 * Decompiled with CFR 0.152.
 */
package org.spongepowered.asm.lib;

public interface Opcodes {
    public static final /* synthetic */ int FREM;
    public static final /* synthetic */ int LMUL;
    public static final /* synthetic */ int ACC_ENUM;
    public static final /* synthetic */ int ANEWARRAY;
    public static final /* synthetic */ int LSHR;
    public static final /* synthetic */ int H_INVOKEVIRTUAL;
    public static final /* synthetic */ int DSUB;
    public static final /* synthetic */ int IFNE;
    public static final /* synthetic */ int ACC_SYNCHRONIZED;
    public static final /* synthetic */ int ICONST_0;
    public static final /* synthetic */ Integer NULL;
    public static final /* synthetic */ int PUTFIELD;
    public static final /* synthetic */ int BALOAD;
    public static final /* synthetic */ int IALOAD;
    public static final /* synthetic */ int F_SAME1;
    public static final /* synthetic */ int LCONST_0;
    public static final /* synthetic */ int I2S;
    public static final /* synthetic */ int DUP2;
    public static final /* synthetic */ int DMUL;
    public static final /* synthetic */ int ALOAD;
    public static final /* synthetic */ int DADD;
    public static final /* synthetic */ int INVOKESPECIAL;
    public static final /* synthetic */ int T_BOOLEAN;
    public static final /* synthetic */ int T_CHAR;
    public static final /* synthetic */ int DUP_X1;
    public static final /* synthetic */ int IUSHR;
    public static final /* synthetic */ int LREM;
    public static final /* synthetic */ int V1_7;
    public static final /* synthetic */ int L2F;
    public static final /* synthetic */ int DNEG;
    public static final /* synthetic */ int LALOAD;
    public static final /* synthetic */ int IOR;
    public static final /* synthetic */ int ACC_INTERFACE;
    public static final /* synthetic */ int GETSTATIC;
    public static final /* synthetic */ int ACC_PROTECTED;
    public static final /* synthetic */ int NEW;
    public static final /* synthetic */ int MONITOREXIT;
    public static final /* synthetic */ int T_INT;
    public static final /* synthetic */ int F_APPEND;
    public static final /* synthetic */ int FALOAD;
    public static final /* synthetic */ int ACC_PRIVATE;
    public static final /* synthetic */ int T_DOUBLE;
    public static final /* synthetic */ int LLOAD;
    public static final /* synthetic */ int FCONST_2;
    public static final /* synthetic */ int ISTORE;
    public static final /* synthetic */ int IXOR;
    public static final /* synthetic */ int FCMPG;
    public static final /* synthetic */ int LADD;
    public static final /* synthetic */ int ISUB;
    public static final /* synthetic */ int IASTORE;
    public static final /* synthetic */ int INEG;
    public static final /* synthetic */ int ACC_STRICT;
    public static final /* synthetic */ int DREM;
    public static final /* synthetic */ int LRETURN;
    public static final /* synthetic */ int INVOKEDYNAMIC;
    public static final /* synthetic */ int V1_1;
    public static final /* synthetic */ int DASTORE;
    public static final /* synthetic */ int LSUB;
    public static final /* synthetic */ int ILOAD;
    public static final /* synthetic */ int IAND;
    public static final /* synthetic */ int IF_ACMPNE;
    public static final /* synthetic */ int DUP2_X2;
    public static final /* synthetic */ int IREM;
    public static final /* synthetic */ int DALOAD;
    public static final /* synthetic */ int ACC_SYNTHETIC;
    public static final /* synthetic */ int DDIV;
    public static final /* synthetic */ int DLOAD;
    public static final /* synthetic */ Integer INTEGER;
    public static final /* synthetic */ int V1_6;
    public static final /* synthetic */ int LOOKUPSWITCH;
    public static final /* synthetic */ int FRETURN;
    public static final /* synthetic */ int PUTSTATIC;
    public static final /* synthetic */ int IF_ICMPGT;
    public static final /* synthetic */ int IF_ICMPLT;
    public static final /* synthetic */ int FASTORE;
    public static final /* synthetic */ int ACC_STATIC;
    public static final /* synthetic */ int ICONST_2;
    public static final /* synthetic */ int BIPUSH;
    public static final /* synthetic */ int LASTORE;
    public static final /* synthetic */ int V1_8;
    public static final /* synthetic */ int IINC;
    public static final /* synthetic */ int ACC_ABSTRACT;
    public static final /* synthetic */ Integer LONG;
    public static final /* synthetic */ int LCMP;
    public static final /* synthetic */ int MULTIANEWARRAY;
    public static final /* synthetic */ int FSUB;
    public static final /* synthetic */ int F_SAME;
    public static final /* synthetic */ int AALOAD;
    public static final /* synthetic */ int LSHL;
    public static final /* synthetic */ int H_PUTSTATIC;
    public static final /* synthetic */ int T_FLOAT;
    public static final /* synthetic */ int IMUL;
    public static final /* synthetic */ int SASTORE;
    public static final /* synthetic */ int D2L;
    public static final /* synthetic */ int H_INVOKEINTERFACE;
    public static final /* synthetic */ int CASTORE;
    public static final /* synthetic */ int FADD;
    public static final /* synthetic */ int SIPUSH;
    public static final /* synthetic */ int LUSHR;
    public static final /* synthetic */ int L2I;
    public static final /* synthetic */ int JSR;
    public static final /* synthetic */ int IFEQ;
    public static final /* synthetic */ int LNEG;
    public static final /* synthetic */ int RETURN;
    public static final /* synthetic */ int ARETURN;
    public static final /* synthetic */ int IADD;
    public static final /* synthetic */ int FCMPL;
    public static final /* synthetic */ int LDC;
    public static final /* synthetic */ int ASM5;
    public static final /* synthetic */ int IF_ICMPEQ;
    public static final /* synthetic */ int NEWARRAY;
    public static final /* synthetic */ int F2D;
    public static final /* synthetic */ int I2D;
    public static final /* synthetic */ int V1_4;
    public static final /* synthetic */ int H_INVOKESPECIAL;
    public static final /* synthetic */ int I2B;
    public static final /* synthetic */ int F2L;
    public static final /* synthetic */ int F_CHOP;
    public static final /* synthetic */ int SALOAD;
    public static final /* synthetic */ int IFGE;
    public static final /* synthetic */ int T_BYTE;
    public static final /* synthetic */ int LSTORE;
    public static final /* synthetic */ int T_SHORT;
    public static final /* synthetic */ int DCMPL;
    public static final /* synthetic */ int LCONST_1;
    public static final /* synthetic */ int FNEG;
    public static final /* synthetic */ int F_NEW;
    public static final /* synthetic */ int D2F;
    public static final /* synthetic */ int T_LONG;
    public static final /* synthetic */ int I2L;
    public static final /* synthetic */ int IDIV;
    public static final /* synthetic */ int AASTORE;
    public static final /* synthetic */ int ACC_MANDATED;
    public static final /* synthetic */ int DUP2_X1;
    public static final /* synthetic */ int IF_ACMPEQ;
    public static final /* synthetic */ int ACC_PUBLIC;
    public static final /* synthetic */ int ATHROW;
    public static final /* synthetic */ int GOTO;
    public static final /* synthetic */ int LDIV;
    public static final /* synthetic */ int F_FULL;
    public static final /* synthetic */ int ICONST_M1;
    public static final /* synthetic */ int RET;
    public static final /* synthetic */ int ACC_NATIVE;
    public static final /* synthetic */ int ICONST_1;
    public static final /* synthetic */ int ASM4;
    public static final /* synthetic */ int ACC_DEPRECATED;
    public static final /* synthetic */ int H_INVOKESTATIC;
    public static final /* synthetic */ int ACC_BRIDGE;
    public static final /* synthetic */ int ASTORE;
    public static final /* synthetic */ int INVOKEINTERFACE;
    public static final /* synthetic */ int DSTORE;
    public static final /* synthetic */ int IRETURN;
    public static final /* synthetic */ int LAND;
    public static final /* synthetic */ int V1_2;
    public static final /* synthetic */ int H_NEWINVOKESPECIAL;
    public static final /* synthetic */ int IF_ICMPGE;
    public static final /* synthetic */ int INSTANCEOF;
    public static final /* synthetic */ Integer TOP;
    public static final /* synthetic */ int DCONST_1;
    public static final /* synthetic */ int I2F;
    public static final /* synthetic */ int ACC_TRANSIENT;
    public static final /* synthetic */ int ARRAYLENGTH;
    public static final /* synthetic */ int CHECKCAST;
    public static final /* synthetic */ int H_PUTFIELD;
    public static final /* synthetic */ int INVOKEVIRTUAL;
    public static final /* synthetic */ int ACC_VOLATILE;
    public static final /* synthetic */ int TABLESWITCH;
    public static final /* synthetic */ int GETFIELD;
    public static final /* synthetic */ int ISHL;
    public static final /* synthetic */ int F2I;
    public static final /* synthetic */ Integer DOUBLE;
    public static final /* synthetic */ int ICONST_4;
    public static final /* synthetic */ int ISHR;
    public static final /* synthetic */ Integer UNINITIALIZED_THIS;
    public static final /* synthetic */ int ICONST_5;
    public static final /* synthetic */ int IFNONNULL;
    public static final /* synthetic */ Integer FLOAT;
    public static final /* synthetic */ int I2C;
    public static final /* synthetic */ int FMUL;
    public static final /* synthetic */ int NOP;
    public static final /* synthetic */ int ACC_FINAL;
    public static final /* synthetic */ int INVOKESTATIC;
    public static final /* synthetic */ int V1_3;
    public static final /* synthetic */ int ACC_VARARGS;
    public static final /* synthetic */ int FCONST_0;
    public static final /* synthetic */ int POP2;
    public static final /* synthetic */ int DCONST_0;
    public static final /* synthetic */ int ACONST_NULL;
    public static final /* synthetic */ int DRETURN;
    public static final /* synthetic */ int ICONST_3;
    public static final /* synthetic */ int FLOAD;
    public static final /* synthetic */ int LOR;
    public static final /* synthetic */ int D2I;
    public static final /* synthetic */ int V1_5;
    public static final /* synthetic */ int SWAP;
    public static final /* synthetic */ int FCONST_1;
    public static final /* synthetic */ int CALOAD;
    public static final /* synthetic */ int DUP;
    public static final /* synthetic */ int IFGT;
    public static final /* synthetic */ int IF_ICMPNE;
    public static final /* synthetic */ int IFLT;
    public static final /* synthetic */ int LXOR;
    public static final /* synthetic */ int FDIV;
    public static final /* synthetic */ int H_GETFIELD;
    public static final /* synthetic */ int IFNULL;
    public static final /* synthetic */ int DCMPG;
    public static final /* synthetic */ int ACC_SUPER;
    public static final /* synthetic */ int IFLE;
    public static final /* synthetic */ int L2D;
    public static final /* synthetic */ int FSTORE;
    public static final /* synthetic */ int IF_ICMPLE;
    public static final /* synthetic */ int MONITORENTER;
    public static final /* synthetic */ int BASTORE;
    public static final /* synthetic */ int POP;
    public static final /* synthetic */ int ACC_ANNOTATION;
    public static final /* synthetic */ int H_GETSTATIC;
    public static final /* synthetic */ int DUP_X2;

    static {
        DMUL = 107;
        I2L = 133;
        FRETURN = 174;
        INVOKEINTERFACE = 185;
        DUP2 = 92;
        ALOAD = 25;
        IINC = 132;
        IFLE = 158;
        LSUB = 101;
        POP = 87;
        MULTIANEWARRAY = 197;
        SALOAD = 53;
        RET = 169;
        I2D = 135;
        LRETURN = 173;
        ICONST_2 = 5;
        IF_ICMPNE = 160;
        FADD = 98;
        FMUL = 106;
        ISTORE = 54;
        L2F = 137;
        IFNE = 154;
        IALOAD = 46;
        ICONST_4 = 7;
        DUP2_X2 = 94;
        MONITORENTER = 194;
        T_CHAR = 5;
        F_SAME = 3;
        H_PUTFIELD = 3;
        ACC_INTERFACE = 512;
        BASTORE = 84;
        LXOR = 131;
        LSHL = 121;
        LCMP = 148;
        V1_6 = 50;
        ICONST_3 = 6;
        INVOKESTATIC = 184;
        INEG = 116;
        ACC_ANNOTATION = 8192;
        FSTORE = 56;
        IF_ACMPEQ = 165;
        LCONST_0 = 9;
        LSHR = 123;
        T_DOUBLE = 7;
        IFNONNULL = 199;
        F2L = 140;
        ACC_PRIVATE = 2;
        AASTORE = 83;
        H_INVOKEVIRTUAL = 5;
        IFLT = 155;
        IREM = 112;
        H_GETFIELD = 1;
        POP2 = 88;
        LNEG = 117;
        F2D = 141;
        IUSHR = 124;
        FASTORE = 81;
        NOP = 0;
        V1_5 = 49;
        ASM4 = 262144;
        CALOAD = 52;
        F_APPEND = 1;
        DADD = 99;
        LSTORE = 55;
        NEW = 187;
        ILOAD = 21;
        CASTORE = 85;
        ICONST_5 = 8;
        IF_ACMPNE = 166;
        IASTORE = 79;
        I2F = 134;
        FCONST_2 = 13;
        ISHL = 120;
        DDIV = 111;
        IADD = 96;
        ARRAYLENGTH = 190;
        LCONST_1 = 10;
        DCMPG = 152;
        INSTANCEOF = 193;
        V1_1 = 196653;
        ATHROW = 191;
        T_BOOLEAN = 4;
        ACC_PUBLIC = 1;
        ACC_STRICT = 2048;
        ACC_VARARGS = 128;
        JSR = 168;
        ACC_FINAL = 16;
        IFGT = 157;
        FDIV = 110;
        DCMPL = 151;
        F_FULL = 0;
        D2I = 142;
        LMUL = 105;
        DASTORE = 82;
        SWAP = 95;
        FALOAD = 48;
        V1_2 = 46;
        PUTFIELD = 181;
        ACC_SUPER = 32;
        IFNULL = 198;
        LAND = 127;
        T_FLOAT = 6;
        ICONST_1 = 4;
        GETFIELD = 180;
        H_PUTSTATIC = 4;
        L2D = 138;
        FNEG = 118;
        RETURN = 177;
        IRETURN = 172;
        IF_ICMPGE = 162;
        ACC_NATIVE = 256;
        IF_ICMPLT = 161;
        FCMPG = 150;
        ACC_PROTECTED = 4;
        FCONST_1 = 12;
        IDIV = 108;
        H_INVOKEINTERFACE = 9;
        DREM = 115;
        ICONST_0 = 3;
        GETSTATIC = 178;
        LALOAD = 47;
        ISUB = 100;
        ACC_SYNTHETIC = 4096;
        D2L = 143;
        I2B = 145;
        ACC_TRANSIENT = 128;
        T_SHORT = 9;
        V1_3 = 47;
        FREM = 114;
        AALOAD = 50;
        ACC_BRIDGE = 64;
        IOR = 128;
        IMUL = 104;
        IF_ICMPLE = 164;
        I2S = 147;
        DUP = 89;
        DNEG = 119;
        TABLESWITCH = 170;
        INVOKEVIRTUAL = 182;
        IFEQ = 153;
        ARETURN = 176;
        ACC_STATIC = 8;
        LLOAD = 22;
        CHECKCAST = 192;
        LOOKUPSWITCH = 171;
        PUTSTATIC = 179;
        LDIV = 109;
        DSUB = 103;
        D2F = 144;
        ASM5 = 327680;
        DUP_X2 = 91;
        LASTORE = 80;
        ISHR = 122;
        IXOR = 130;
        V1_4 = 48;
        H_INVOKESTATIC = 6;
        ACC_DEPRECATED = 131072;
        ACC_ENUM = 16384;
        H_NEWINVOKESPECIAL = 8;
        LADD = 97;
        ACC_ABSTRACT = 1024;
        T_BYTE = 8;
        ICONST_M1 = 2;
        FSUB = 102;
        ACC_SYNCHRONIZED = 32;
        F_NEW = -1;
        FCONST_0 = 11;
        H_INVOKESPECIAL = 7;
        ANEWARRAY = 189;
        ACC_MANDATED = 32768;
        T_INT = 10;
        T_LONG = 11;
        DLOAD = 24;
        DSTORE = 57;
        IAND = 126;
        LOR = 129;
        SASTORE = 86;
        F2I = 139;
        H_GETSTATIC = 2;
        DRETURN = 175;
        NEWARRAY = 188;
        ASTORE = 58;
        GOTO = 167;
        IF_ICMPEQ = 159;
        LUSHR = 125;
        LREM = 113;
        F_SAME1 = 4;
        DUP2_X1 = 93;
        BALOAD = 51;
        L2I = 136;
        DCONST_1 = 15;
        BIPUSH = 16;
        FLOAD = 23;
        DALOAD = 49;
        SIPUSH = 17;
        IF_ICMPGT = 163;
        INVOKEDYNAMIC = 186;
        MONITOREXIT = 195;
        I2C = 146;
        DCONST_0 = 14;
        ACC_VOLATILE = 64;
        ACONST_NULL = 1;
        V1_8 = 52;
        FCMPL = 149;
        V1_7 = 51;
        IFGE = 156;
        DUP_X1 = 90;
        INVOKESPECIAL = 183;
        F_CHOP = 2;
        LDC = 18;
        TOP = new Integer(0);
        INTEGER = new Integer(1);
        FLOAT = new Integer(2);
        DOUBLE = new Integer(3);
        LONG = new Integer(4);
        NULL = new Integer(5);
        UNINITIALIZED_THIS = new Integer(6);
    }
}

